apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: wego-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://weaveworks.github.io/weave-gitops-profile-examples
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-1
  name: test-1-prometheus
  namespace: wego-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: weaveworks-charts
        namespace: wego-system
      version: 0.0.7
  interval: 1m0s
  values:
    kube-prometheus-stack:
      alertmanager:
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /$1
            nginx.ingress.kubernetes.io/use-regex: "true"
          enabled: true
          paths:
          - /alertmanager/?(.*)
      enabled: true
      grafana:
        grafana.ini:
          server:
            root_url: https://localhost:3000/grafana/
            serve_from_sub_path: true
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
          enabled: true
          path: /grafana/?(.*)
status: {}
