---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-test-mgmt-repo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-test-mgmt-repo
  url: ssh://git@github.com/pfcurtis/test-mgmt-repo.git

