---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-auto-github-test-mgmt-repo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/pfcurtis/test-mgmt-repo.git

